backend:
  name: github
  branch: master
  repo: danielroe/vuejs-berlin

media_folder: public/images
collections:
  - name: content
    label: Content for presentation
    folder: src/content
    create: True
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
